# 手柄数据

# 手柄接管中
bool takeover

#原始数据
bool a
bool b
bool x
bool y
bool lb
bool rb
bool back
bool start
bool up
bool down
bool left
bool right
bool lp
bool rp

float32 lx
float32 ly
float32 rx
float32 ry
float32 lt
float32 rt

#处理后的数据，todo暂未开发
bool a_press    # 按下
bool a_release  # 释放
bool b_press
bool b_release
bool x_press
bool x_release
bool y_press
bool y_release
bool lb_press
bool lb_release
bool back_press
bool back_release
bool start_press
bool start_release
bool up_press
bool up_release
bool down_press
bool down_release
bool left_press
bool left_release
bool right_press
bool right_release
bool lp_press
bool lp_release
