// Generated by gencpp from file robot_msgs/MotorState.msg
// DO NOT EDIT!

#ifndef ROBOT_MSGS_MESSAGE_MOTORSTATE_H
#define ROBOT_MSGS_MESSAGE_MOTORSTATE_H

#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <memory>
#include <string>
#include <vector>

namespace robot_msgs
{
template <class ContainerAllocator>
struct MotorState_
{
    typedef MotorState_<ContainerAllocator> Type;

    MotorState_() : alpha(0.0), torq(0.0), ddq(0.0), blta(0.0), cur(0.0) {}
    MotorState_(const ContainerAllocator& _alloc) : alpha(0.0), torq(0.0), ddq(0.0), blta(0.0), cur(0.0) { (void)_alloc; }

    typedef float _alpha_type;
    _alpha_type alpha;

    typedef float _torq_type;
    _torq_type torq;

    typedef float _ddq_type;
    _ddq_type ddq;

    typedef float _tauEst_type;
    _tauEst_type blta;

    typedef float _cur_type;
    _cur_type cur;

    typedef boost::shared_ptr< ::robot_msgs::MotorState_<ContainerAllocator> > Ptr;
    typedef boost::shared_ptr< ::robot_msgs::MotorState_<ContainerAllocator> const> ConstPtr;

};  // struct MotorState_

typedef ::robot_msgs::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::robot_msgs::MotorState> MotorStatePtr;
typedef boost::shared_ptr< ::robot_msgs::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition

template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MotorState_<ContainerAllocator>& v)
{
    ros::message_operations::Printer< ::robot_msgs::MotorState_<ContainerAllocator> >::stream(s, "", v);
    return s;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MotorState_<ContainerAllocator1>& lhs, const ::robot_msgs::MotorState_<ContainerAllocator2>& rhs)
{
    return lhs.alpha == rhs.alpha && lhs.torq == rhs.torq && lhs.ddq == rhs.ddq && lhs.blta == rhs.blta && lhs.cur == rhs.cur;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MotorState_<ContainerAllocator1>& lhs, const ::robot_msgs::MotorState_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}

}  // namespace robot_msgs

namespace ros
{
namespace message_traits
{

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorState_<ContainerAllocator> > : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorState_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorState_<ContainerAllocator> > : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorState_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorState_<ContainerAllocator> > : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorState_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MotorState_<ContainerAllocator> >
{
    static const char* value() { return "7b27035d8fd4c0437680bec7c6cb2db9"; }

    static const char* value(const ::robot_msgs::MotorState_<ContainerAllocator>&) { return value(); }
    static const uint64_t static_value1 = 0x7b27035d8fd4c043ULL;
    static const uint64_t static_value2 = 0x7680bec7c6cb2db9ULL;
};

template <class ContainerAllocator>
struct DataType< ::robot_msgs::MotorState_<ContainerAllocator> >
{
    static const char* value() { return "robot_msgs/MotorState"; }

    static const char* value(const ::robot_msgs::MotorState_<ContainerAllocator>&) { return value(); }
};

template <class ContainerAllocator>
struct Definition< ::robot_msgs::MotorState_<ContainerAllocator> >
{
    static const char* value()
    {
        return "float32 alpha            # motor current position (rad)\n"
               "float32 torq           # motor current speed (rad/s)\n"
               "float32 ddq          # motor current speed (rad/s)\n"
               "float32 blta       # current estimated output torque (N*m)\n"
               "float32 cur          # current estimated output cur (N*m)\n";
    }

    static const char* value(const ::robot_msgs::MotorState_<ContainerAllocator>&) { return value(); }
};

}  // namespace message_traits
}  // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer< ::robot_msgs::MotorState_<ContainerAllocator> >
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.alpha);
        stream.next(m.torq);
        stream.next(m.ddq);
        stream.next(m.blta);
        stream.next(m.cur);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
};  // struct MotorState_

}  // namespace serialization
}  // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer< ::robot_msgs::MotorState_<ContainerAllocator> >
{
    template <typename Stream>
    static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MotorState_<ContainerAllocator>& v)
    {
        s << indent << "alpha: ";
        Printer<float>::stream(s, indent + "  ", v.alpha);
        s << indent << "torq: ";
        Printer<float>::stream(s, indent + "  ", v.torq);
        s << indent << "ddq: ";
        Printer<float>::stream(s, indent + "  ", v.ddq);
        s << indent << "blta: ";
        Printer<float>::stream(s, indent + "  ", v.blta);
        s << indent << "cur: ";
        Printer<float>::stream(s, indent + "  ", v.cur);
    }
};

}  // namespace message_operations
}  // namespace ros

#endif  // ROBOT_MSGS_MESSAGE_MOTORSTATE_H
