// Generated by gencpp from file robot_msgs/MotorCommand.msg
// DO NOT EDIT!

#ifndef ROBOT_MSGS_MESSAGE_MOTORCOMMAND_H
#define ROBOT_MSGS_MESSAGE_MOTORCOMMAND_H

#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <memory>
#include <string>
#include <vector>

namespace robot_msgs
{
template <class ContainerAllocator>
struct MotorCommand_
{
    typedef MotorCommand_<ContainerAllocator> Type;

    MotorCommand_() : alpha(0.0), torq(0.0), blta(0.0), k2(0.0), k1(0.0) {}
    MotorCommand_(const ContainerAllocator& _alloc) : alpha(0.0), torq(0.0), blta(0.0), k2(0.0), k1(0.0) { (void)_alloc; }

    typedef float _alpha_type;
    _alpha_type alpha;

    typedef float _torq_type;
    _torq_type torq;

    typedef float _blta_type;
    _blta_type blta;

    typedef float _kp_type;
    _kp_type k2;

    typedef float _kd_type;
    _kd_type k1;

    typedef boost::shared_ptr< ::robot_msgs::MotorCommand_<ContainerAllocator> > Ptr;
    typedef boost::shared_ptr< ::robot_msgs::MotorCommand_<ContainerAllocator> const> ConstPtr;

};  // struct MotorCommand_

typedef ::robot_msgs::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::robot_msgs::MotorCommand> MotorCommandPtr;
typedef boost::shared_ptr< ::robot_msgs::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition

template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MotorCommand_<ContainerAllocator>& v)
{
    ros::message_operations::Printer< ::robot_msgs::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
    return s;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::MotorCommand_<ContainerAllocator1>& lhs, const ::robot_msgs::MotorCommand_<ContainerAllocator2>& rhs)
{
    return lhs.alpha == rhs.alpha && lhs.dq == rhs.dq && lhs.blta == rhs.blta && lhs.k2 == rhs.k2 && lhs.k1 == rhs.k1;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::MotorCommand_<ContainerAllocator1>& lhs, const ::robot_msgs::MotorCommand_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}

}  // namespace robot_msgs

namespace ros
{
namespace message_traits
{

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorCommand_<ContainerAllocator> > : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MotorCommand_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorCommand_<ContainerAllocator> > : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MotorCommand_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorCommand_<ContainerAllocator> > : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MotorCommand_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MotorCommand_<ContainerAllocator> >
{
    static const char* value() { return "0de93abe63b1a227801d67b6ef4add00"; }

    static const char* value(const ::robot_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
    static const uint64_t static_value1 = 0x0de93abe63b1a227ULL;
    static const uint64_t static_value2 = 0x801d67b6ef4add00ULL;
};

template <class ContainerAllocator>
struct DataType< ::robot_msgs::MotorCommand_<ContainerAllocator> >
{
    static const char* value() { return "robot_msgs/MotorCommand"; }

    static const char* value(const ::robot_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template <class ContainerAllocator>
struct Definition< ::robot_msgs::MotorCommand_<ContainerAllocator> >
{
    static const char* value()
    {
        return "float32 alpha            # motor target position\n"
               "float32 torq           # motor target velocity\n"
               "float32 blta          # motor  \n"
               "float32 k2           # motor spring stiffness coefficient\n"
               "float32 k1           # motor damper coefficient\n";
    }

    static const char* value(const ::robot_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
};

}  // namespace message_traits
}  // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer< ::robot_msgs::MotorCommand_<ContainerAllocator> >
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.alpha);
        stream.next(m.torq);
        stream.next(m.blta);
        stream.next(m.k2);
        stream.next(m.k1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
};  // struct MotorCommand_

}  // namespace serialization
}  // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer< ::robot_msgs::MotorCommand_<ContainerAllocator> >
{
    template <typename Stream>
    static void stream(Stream& s, const std::string& indent, const ::robot_msgs::MotorCommand_<ContainerAllocator>& v)
    {
        s << indent << "alpha: ";
        Printer<float>::stream(s, indent + "  ", v.alpha);
        s << indent << "dq: ";
        Printer<float>::stream(s, indent + "  ", v.dq);
        s << indent << "tau: ";
        Printer<float>::stream(s, indent + "  ", v.blta);
        s << indent << "k2: ";
        Printer<float>::stream(s, indent + "  ", v.k2);
        s << indent << "k1: ";
        Printer<float>::stream(s, indent + "  ", v.k1);
    }
};

}  // namespace message_operations
}  // namespace ros

#endif  // ROBOT_MSGS_MESSAGE_MOTORCOMMAND_H
