#!/bin/bash

#=============================================================================
# Layer 版本信息生成脚本
# 用途：在 Jenkins 上为所有 layer 预生成版本信息文件
# 作者：唐文浩
# 日期：2025-10-11
#=============================================================================

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_header() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}$1${NC}"
    echo -e "${GREEN}========================================${NC}"
}

print_header "生成 Layer 版本信息"

# 获取构建时间戳
BUILD_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
BUILD_TIMESTAMP_SHORT=$(date '+%Y%m%d_%H%M%S')

# 统计
TOTAL_LAYERS=0
SUCCESS_LAYERS=0
FAILED_LAYERS=0

# 遍历所有 layer 目录
for layer_path in src/*/; do
    if [ ! -d "$layer_path" ]; then
        continue
    fi

    LAYER_NAME=$(basename "$layer_path")
    TOTAL_LAYERS=$((TOTAL_LAYERS + 1))

    print_info "处理 layer: ${LAYER_NAME}"

    # 检查是否是 git 仓库
    if [ ! -d "${layer_path}/.git" ]; then
        print_warning "  ${LAYER_NAME} 不是 Git 仓库，跳过"
        FAILED_LAYERS=$((FAILED_LAYERS + 1))
        continue
    fi

    # 进入 layer 目录
    cd "$layer_path"

    # 获取 Git 信息
    GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
    GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
    GIT_COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
    GIT_DIRTY=""

    # 检查是否有未提交的修改
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
        GIT_DIRTY="-dirty"
    fi

    # 生成版本信息文件
    cat > VERSION_INFO.txt <<EOF
# Layer Version Information
# Auto-generated by Jenkins CI/CD
# Generation Time: ${BUILD_TIMESTAMP}

GIT_BRANCH=${GIT_BRANCH}
GIT_COMMIT=${GIT_COMMIT}
GIT_COMMIT_SHORT=${GIT_COMMIT_SHORT}${GIT_DIRTY}
GIT_TAG=${GIT_TAG}
LAYER_NAME=${LAYER_NAME}
BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
BUILD_TIMESTAMP_SHORT=${BUILD_TIMESTAMP_SHORT}
EOF

    if [ $? -eq 0 ]; then
        print_success "  ✅ ${LAYER_NAME}: ${GIT_BRANCH}@${GIT_COMMIT_SHORT}${GIT_DIRTY}"
        SUCCESS_LAYERS=$((SUCCESS_LAYERS + 1))
    else
        print_error "  ❌ ${LAYER_NAME}: 生成失败"
        FAILED_LAYERS=$((FAILED_LAYERS + 1))
    fi

    # 返回根目录
    cd - > /dev/null
done

print_header "版本信息生成完成"
echo ""
echo "总计: ${TOTAL_LAYERS} 个 layer"
echo "成功: ${GREEN}${SUCCESS_LAYERS}${NC} 个"
echo "失败: ${RED}${FAILED_LAYERS}${NC} 个"
echo ""

if [ $SUCCESS_LAYERS -eq 0 ]; then
    print_error "没有成功生成任何版本信息！"
    exit 1
fi

print_info "生成的版本信息文件："
find src/ -name "VERSION_INFO.txt" -type f

print_success "版本信息生成完成！"
